[package]
name = "xcm-simulator"
description = "Test kit to simulate cross-chain message passing and XCM execution"
edition = "2021"
repository = "https://github.com/paritytech/polkadot.git"
version = "0.9.36"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
paste = "1.0.7"

frame-support = {  path="../../frame/support", default-features = false } 
sp-io = { path="../../primitives/io", default-features = false}
sp-std = { path="../../primitives/std", default-features = false}

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
polkadot-core-primitives ={ git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
polkadot-parachain ={ git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
