[package]
name = "polkadot-runtime-metrics"
version = "0.9.36"
edition = "2021"

[dependencies]
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
parity-scale-codec = { version = "3.4.0", default-features = false }
primitives = { package = "polkadot-primitives", path = "../../xcm-primitives", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false, optional = true }

bs58 = { version = "0.4.0", default-features = false, features = ["alloc"] }

[features]  
default = ["std"]
std = [
	"sp-std/std",
	"sp-tracing/std",
    "parity-scale-codec/std",
    "primitives/std",
    "bs58/std"
]
runtime-metrics = ["sp-tracing/with-tracing", "frame-benchmarking"]
