[package]
name = "pallet-bridge-dispatch"
description = "A Substrate Runtime module that dispatches a bridge message, treating it simply as encoded Call"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }


# Bridge dependencies

bp-message-dispatch = { path = "../../primitives_bridge/message-dispatch", default-features = false }
bp-runtime = { path = "../../primitives_bridge/runtime", default-features = false }

# Substrate Dependencies

frame-support = { version = "4.0.0-dev", default-features = false, path = "../../frame/support" }
#frame-support2 = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", path = "../../frame/system", default-features = false }
sp-core = { version = "7.0.0", default-features = false, path = "../../primitives/core" }
sp-std = { version = "5.0.0", default-features = false, path = "../../primitives/std" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../primitives/runtime" }

[dev-dependencies]
sp-io = { version = "7.0.0", default-features = false, path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"bp-message-dispatch/std",
	"bp-runtime/std",
	"frame-support/std",
	#"frame-support2/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
