[package]
name = "bridge-runtime-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
ed25519-dalek = { version = "1.0", default-features = false, optional = true }
hash-db = { version = "0.15.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
static_assertions = { version = "1.1", optional = true }

# Bridge dependencies

bp-message-dispatch = { path = "../../primitives_bridge/message-dispatch", default-features = false }
bp-messages = { path = "../../primitives_bridge/messages", default-features = false }
bp-runtime = { path = "../../primitives_bridge/runtime", default-features = false }
pallet-bridge-dispatch = { path = "../../modules/dispatch", default-features = false }
pallet-bridge-grandpa = { path = "../../modules/grandpa", default-features = false }
pallet-bridge-messages = { path = "../../modules/messages", default-features = false }

#pallet 

frame-support = { version = "4.0.0-dev", default-features = false, path = "../../frame/support" }
frame-support2 = { version = "4.0.0-dev", default-features = false, path = "../../modules/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../frame/system" }
pallet-balances = { version = "4.0.0-dev", default-features = false, path = "../../frame/balances", optional = true }
pallet-transaction-payment = { version = "4.0.0-dev", default-features = false, path = "../../frame/transaction-payment" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../primitives/api"}
sp-core = { version = "7.0.0", default-features = false, path = "../../primitives/core" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../primitives/runtime"}
sp-state-machine = {version = "0.13.0", default-features = false, path = "../../primitives/state-machine", optional = true }
sp-std = { version = "5.0.0", default-features = false, path = "../../primitives/std" }
sp-trie = { version = "7.0.0", default-features = false, path = "../../primitives/trie"}
sp-version = {version = "5.0.0", default-features = false, path = "../../primitives/version",optional = true }


[features]
default = ["std"]
std = [
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"hash-db/std",
	"pallet-bridge-dispatch/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"frame-support2/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"ed25519-dalek/u64_backend",
	"pallet-balances",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-state-machine",
	"sp-version",
]
integrity-test = [
	"static_assertions",
]
